### ISSUE TITLE
Creating a node on DigitalOcean failed when region not specified

### ISSUE THREAD

**Issue by derekpierre** [nucypher/nucypher-ops#9]
To resolve I had to specify a specific region using the region parameter parameter i.e. `--region <REGION>` when running `nucypher-ops nodes create`.

```
  File "/Users/derek/Documents/Github/repos/nucypher-ops/nucypher_ops/cli/nodes.py", line 53, in create
    deployer.create_nodes(names)
  File "/Users/derek/Documents/Github/repos/nucypher-ops/nucypher_ops/ops/fleet_ops.py", line 351, in create_nodes
    node_data = self.create_new_node(node_name)
  File "/Users/derek/Documents/Github/repos/nucypher-ops/nucypher_ops/ops/fleet_ops.py", line 1037, in create_new_node
    raise BaseException("Error creating resources in DigitalOcean")
BaseException: Error creating resources in DigitalOcean
```

Perhaps the randomized region can be problematic depending on the random region determined? See https://docs.digitalocean.com/products/platform/availability-matrix/

```
Due to limited capacity in NYC2, AMS2, SFO1, and SFO2, only users who already have existing resources in those regions can create more resources there.
```

**Comment by vepkenez** [comment]
Hmm that's interesting.

I am only including these in the random choice...
            'NYC1',
            'NYC3',
            'AMS3',
            'SFO3',
            'SGP1',
            'LON1',
            'FRA1',
            'TOR1',
            'BLR'
They must have shadowbanned a new one... 🤔
